### Sign-Up
POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
	"username": "john",
	"email": "john@gmail.com",
	"password": "12345678",
	"roles": ["moderator", "user"]
}


### Sign-In
POST http://localhost:3000/api/auth/signin
Content-Type: application/json

{
	"username": "mod",
	"password": "12345678"
}


### Retrieve Public Content
GET http://localhost:3000/api/test/all


### Access User Content
GET http://localhost:3000/api/test/user


### Access Moderator Content
GET http://localhost:3000/api/test/mod



### Access Admin Content
GET http://localhost:3000/api/test/admin	
