### Without Auth
GET http://localhost:3000/api/


### Login 
POST http://localhost:3000/api/login 


### POST with token
POST http://localhost:3000/api/posts
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJ1c2VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJwcmFkZWVwLnZ3YUBnbWFpbC5jb20ifSwiaWF0IjoxNTkzNzkxNDU3LCJleHAiOjE1OTM3OTE0ODd9.YSVT4jcMtGjA_oGaiCTTEecgnAPBoRLVbn53RBAuFOg
